accounts/urls.py
from django.urls import path
from .views import (
    homepage,
    profile,
    login,
    create_account,
    dashboard,
    GetFactoriesView,
    accounts,
    create_buyer_account,
    about,
    contact,
    services,
    create_factory_account,
    market,
    help,
)

namespace = "accounts"

urlpatterns = [
    path("", homepage, name="homepage"),
    path("profile/", profile, name="profile"),
    path("login/", login, name="login"),
    path("create_account/", create_account, name="create_account"),
    path("dashboard/", dashboard, name="dashboard"),
    path("factories/", GetFactoriesView.as_view(), name="factories"),
    path("GetSarted/", accounts, name="start"),
    path("Buyer/", create_buyer_account, name="buyer"),
    path("about/", about, name="about"),
    path("contact/", contact, name="contact"),
    path("services/", services, name="services"),
    path("Factory/", create_factory_account, name="factory"),
    path("market/", market, name="market"),
    path("help/", help, name="help"),
]

agriproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

namespace = "transactions"

urlpatterns = [
    path("dev/", admin.site.urls),
    path("", include(("accounts.urls", "accounts"), namespace="accounts")),
    path(
        "transactions/",
        include(("transactions.urls", "transactions"), namespace="transactions"),
    ),
    path("feedback/", include(("feedback.urls", "feedback"), namespace="feedback")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/urls.py
from django.urls import path
from .views import CreateEscalation, CreateRawFeedBack, MainFeedBackView

app_name = "feedback"

urlpatterns = [
    path("", CreateRawFeedBack.as_view(), name="createfeedback"),
    path("<int:order_id>/", CreateEscalation.as_view(), name="createescalation"),
    path("main/", MainFeedBackView.as_view(), name="showfeedback"),
]

transactions/urls.py
from django.urls import path
from .views import (
    add_auction,
    view_market,
    view_market_id,
    view_order,
    view_auction,
    chat,
    view_factory,
    AcceptOrderView,
    EnterShipmentInfoView,
    AddShipmentAddressView,
    GetChartView,
    confirmArival,
    DeletAuction,
    CreateAuction,
    GetBuyerChartView,
    ShowAuctionHistory,
    ShowTransactions,
    ShowNotifications,
    TrackOrder,
    CreateOrder,
)

namespace = "transactions"

urlpatterns = [
    path("add_auction/<str:factory_name>/", add_auction, name="add_auction"),
    path("view_market/", view_market, name="view_market"),
    path("view_market/<int:id>/", view_market_id, name="view_market"),
    path("view_order/<int:order_id>/", view_order, name="view_order"),
    path("view_auction/", view_auction, name="view_auction"),
    path("chat/", chat, name="chat"),
    path(
        "view_market/view_factory/<int:factory_id>/", view_factory, name="view_factory"
    ),
    path(
        "view_order/<int:factory_id>/update_order/",
        AcceptOrderView.as_view(),
        name="accept_order",
    ),
    path(
        "shipmentinfo/<int:order_id>/",
        EnterShipmentInfoView.as_view(),
        name="shipmentview",
    ),
    path("ShipmentSaved/", EnterShipmentInfoView.as_view(), name="saveshipment"),
    path(
        "ShipmentAddress/",
        AddShipmentAddressView.as_view(),
        name="addshippmentaddress",
    ),
    path("charts/<str:factory_name>", GetChartView.as_view(), name="charts"),
    path("bcharts/<str:buyer_name>", GetBuyerChartView.as_view(), name="bcharts"),
    path("order-arrived/<int:order_id>", confirmArival, name="confirm"),
    path(
        "auction-remove/<int:auction_id>", DeletAuction.as_view(), name="delete-auction"
    ),
    path("create_auction/", CreateAuction.as_view(), name="create_auction"),
    path(
        "auction_history/<str:factory_name>/",
        ShowAuctionHistory.as_view(),
        name="auction_history",
    ),
    path("<str:factory_name>/", ShowTransactions.as_view(), name="showtransactions",),
    path(
        "notifications/<str:name>/",
        ShowNotifications.as_view(),
        name="shownotifications",
    ),
    path("orders/<str:user_name>/", TrackOrder.as_view(), name="track_orders"),
    path("order/create/", CreateOrder.as_view(), name="order"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User as user_model

User = user_model


class SellerFactory(models.Model):
    date_created = models.DateField(auto_now_add=True, null=True)
    factory_name = models.CharField(max_length=30)
    factory_initials = models.CharField(max_length=10, null=True)

    company_email = models.EmailField()
    phone = models.CharField(max_length=20)
    region = models.CharField(max_length=30)
    country = models.CharField(max_length=30)
    street_name = models.CharField(max_length=40, default="", null=True)
    zip_code = models.CharField(max_length=20, default="", null=True)
    physical_address = models.CharField(max_length=40, default="", null=True)

    trade_license = models.FileField(null=True, blank=True)
    rating = models.IntegerField(null=True)
    factory_logo = models.ImageField(null=True)
    googlemap = models.TextField(null=True)
    factory_bio = models.TextField(default="No bio")
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.factory_name


class SellerFactoryEmployee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    factory = models.ForeignKey(
        SellerFactory, on_delete=models.CASCADE, null=False, blank=False
    )
    profile_picture = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.user.username


class Buyer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    use_case = models.TextField(null = True)
    profile_picture = models.ImageField(blank=True, null=True)
    country = models.CharField(max_length = 20, null = True)
    phone = models.IntegerField(null = True)
    address = models.TextField(null = True)


    def __str__(self):
        return self.user.username


class HomepageSlides(models.Model):
    hq_image = models.ImageField(null=True)
    main_title = models.CharField(max_length=50, blank=True, null=True)
    sub_title = models.CharField(max_length=100, blank=True, null=True)
    content = models.TextField()

    def __str__(self):
        return self.main_title


class BestBlog(models.Model):
    hq_image = models.ImageField(null=True)
    main_title = models.CharField(max_length=50, blank=True, null=True)
    sub_title = models.CharField(max_length=100, blank=True, null=True)
    content = models.TextField()
    link = models.CharField(max_length=100)

    def __str__(self):
        return self.main_title

accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import login as login_user, logout, authenticate
from django.contrib.auth.models import User
from transactions import calenderutil
from django.shortcuts import redirect
from .models import (
    SellerFactoryEmployee,
    SellerFactory,
    HomepageSlides,
    Buyer,
    BestBlog,
)
from backup.models import BackOrder, BackAuction
from django.views.generic import View
from django.urls import reverse
from transactions.models import Order, Auction
from feedback.models import Contact


def homepage(request):
    slides = HomepageSlides.objects.all()
    bestblogs = BestBlog.objects.all()
    return render(request, "homepage.html", {"slides": slides, "bestblogs": bestblogs})


def profile(request):
    return render(request, "profile.html", {})


def about(request):
    return render(request, "about.html", {})


def login(request):
    error = None
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("pass")
        try:
            user = User.objects.get(email=email)
            if user.check_password(password):
                login_user(request, user)
                return redirect("accounts:dashboard")
        except User.DoesNotExist:
            error = "incorrect email or password"
    return render(request, "login.html", {"error": error})


def dashboard(request):
    if request.user.is_authenticated:
        user = request.user
    else:
        return redirect("account:login")
    context = {"user": user}
    try:
        order_queryset = Order.objects.filter(employee=user.sellerfactoryemployee)
        auctionsreal = Auction.objects.filter(
            factory=user.sellerfactoryemployee.factory
        )
        auctions = BackAuction.objects.filter(
            factory=user.sellerfactoryemployee.factory
        )

        n = 0
        for order in order_queryset:
            if order.auction == auctionsreal[0]:
                n += 1
        backauctions = BackAuction.objects.all()
        prices = []
        months_price = []
        months = []

        if not backauctions:
            print("empty")
            backauctions = Auction.objects.filter(
                factory=user.sellerfactoryemployee.factory
            )
            print(backauctions)
        for auction in backauctions:
            price = auction.price_per_tonne
            months_price.append(auction.date)
            prices.append(price)
        sumprice = sum(prices)
        months = calenderutil.getAllMonthsStr()
        try:
            mean_price = sumprice / len(prices)
        except:
            mean_price = 0
        print(prices)
        context = {
            "prices": prices,
            "months_price": months_price,
            "months": months,
            "MeanPrice": round(mean_price, 3),
            "auction_history": backauctions,
        }
        context["auctions"] = auctionsreal
        context["orders"] = n
        context["order_queryset"] = order_queryset
        return render(request, "seller_dashboard.html", context)
    except AttributeError:
        try:
            order_queryset = Order.objects.filter(buyer=user.buyer)
            auctions = []
            tonnes_traded = 0
            ordersmade = len(order_queryset)
            for order in order_queryset:
                auction = order.auction
                if order.arrived:
                    tonnes_traded += order.amount
                if auction not in auctions:
                    auctions.append(auction)

            notifications = []
            for order in order_queryset:
                if order.status == 1 and not order.shipping_address:
                    notification = Notification(
                        1,
                        "view_order",
                        f"Your Order for the {order.auction} has been accepted",
                        order.id,
                        "transactions",
                    )
                    notifications.append(notification)
            bauctions = BackAuction.objects.all()
            if not bauctions:
                for order in Order.objects.filter(buyer=user.buyer):
                    bauctions.append(order.auction)
                if not Order.objects.filter(buyer=user.buyer):
                    bauctions = Auction.objects.all()
            prices = []
            months_price = []
            months = []
            for auction in bauctions:
                price = auction.price_per_tonne
                months_price.append(auction.date)
                prices.append(price)
            sumprice = sum(prices)
            print("sum", sumprice)
            print(months_price)
            months = calenderutil.getAllMonthsStr()
            try:
                mean_price = sumprice / len(prices)
            except:
                mean_price = 0
            context = {
                "prices": prices,
                "months_price": months_price,
                "months": months,
                "MeanPrice": round(mean_price, 3),
                "ordersmade": ordersmade,
                "tonnes_traded": tonnes_traded,
            }
            context["notifycount"] = len(notifications)

            context["auctions"] = auctions
            context["order_queryset"] = order_queryset

            context["notifications"] = notifications

            orders = Order.objects.filter(buyer=user.buyer)
            context["orders"] = len(orders)
            context["pending"] = len(Order.objects.filter(buyer=user.buyer, status=0))
            context["confirmed"] = len(Order.objects.filter(buyer=user.buyer, status=1))
            context["processed"] = len(Order.objects.filter(buyer=user.buyer, status=2))
            context["completed"] = len(Order.objects.filter(buyer=user.buyer, status=3))
            factories = []
            y = BackOrder.objects.all()
            ls = []
            for order in y:
                factory = order.auction.factory
                if factory not in ls:
                    ls.append(factory)
            context["history_factories"] = ls
            for order in order_queryset:
                if order.employee.factory not in factories:
                    factories.append(order.employee.factory)
            context["factories"] = factories
        except:
            return redirect("/login")
        return render(request, "buyer_dashboard.html", context)


def create_account(request):
    factory_queryset = SellerFactory.objects.all()
    return render(
        request, "create_seller_account.html", {"factory_queryset": factory_queryset}
    )


class Notification:
    def __init__(self, type, action, messsage, id, app_name):
        self.type = type
        self.action = action
        self.message = messsage
        self.id = id
        self.app_name = app_name


class GetFactoriesView(View):
    def get(self, request, *args, **kwargs):
        context = {"factories": SellerFactory.objects.all()}
        return render(request, "factories.html", context)


def create_buyer_account(request):
    print("nothing received")
    if request.method == "POST":
        print("stuff received")
        if (
            request.POST["username"]
            and request.POST["email"]
            and request.POST["pass"]
            and request.POST["repeatpass"]
            and request.POST["country"]
            and request.POST["address"]
            and request.POST["phone"]
        ):
            email = request.POST["email"]
            username = request.POST["username"]
            password = request.POST["pass"]
            repeat_password = request.POST["repeatpass"]
            country = request.POST["country"]
            phone = request.POST["phone"]
            address = request.POST["address"]
            profile_photo = request.POST["profilepicture"]
            email_queryset = User.objects.filter(email=email)
            if email_queryset.__len__() == 0:
                if password == repeat_password:
                    user = User.objects.create(username=username, email=email)
                    user.set_password(password)
                    user.save()
                    buyer = Buyer.objects.create(
                        user=user,
                        country=country,
                        address=address,
                        profile_picture=profile_photo,
                        phone=phone,
                    )
                    buyer.save()
                    if user.is_authenticated:
                        login_user(request, user)
                    return redirect("/dashboard")
                else:
                    print("passwords do not match")
            else:
                print("a user with that email already exists")

    return render(request, "create_buyer_account.html", {})


def create_factory_account(request):
    if request.method == "POST":
        errors = []
        print(request.POST.keys())

        def AccountDetailsValid():
            errors = []
            valid = True
            try:
                email = request.POST["Email"]
            except:
                valid = False
                errors.append("email")
            print("1")
            try:
                firstname = request.POST["firstname"]
            except:
                valid = False
                errors.append("firstname")
            print("3")
            try:
                lastname = request.POST["lastname"]
            except:
                valid = False
                errors.append("lastname")
            print("4")
            try:
                repassword = request.POST["retypepass"]
            except:
                valid = False
                errors.append("enter all passwords")
            print("5")
            print("6")
            print(valid, errors)
            return valid

        try:
            print("trying")

accounts/templates/buyer_dashboard.html
{% extends 'base.html' %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'toastr/toastr.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/mine.css'%}">
{% endblock style %}
{% block content %} {% load static %}
<script>
  hideLoading()
</script>
<div class="main">
  <!-- MAIN CONTENT -->
  <div class="main-content">
    <div class="container-fluid">
      <!-- OVERVIEW -->
      <div class="panel-body">
        <div class="row">
          <div class="col-md-3 orange-border panel-body text-center" style="margin-right: .5%;">
            <i class="lnr lnr-briefcase" style="font-size: 230%; color: orange;"></i>
            <p class="title blue">Orders</p>
            {{ordersmade}} | {{processed}} processed
          </div>
          <div class="col-md-4  orange-border panel-body text-center" style="margin-right: .5%;">
            <i class="lnr lnr-checkmark-circle" style="font-size: 230%; color: rgb(4, 207, 4);"></i>
            <p class="title blue">Tonnes Traded</p>
            {{tonnes_traded}} T
          </div>
          <div class="col-md-4  orange-border panel-body text-center">
            <i class="lnr lnr-chart-bars" style="font-size: 230%; color: orange;"></i>
            <p class="title blue">Market Price</p>
            ${{MeanPrice}} Per Metric Tonne
          </div>
        </div>
      </div><br>
      <div class="orange-border panel-body ftco-animate">
        <h2 class="orange livetext-mega">suggested factories</h2>
        {%if not history_factories%}
        <a href="{%url 'transactions:view_market'%}">No Transaction History, click to view market!</a><br><br>
        {%endif%}
        {%for factory in history_factories%}
        <div class="panel-body dark-l selector-dark">
          <img src="{{factory.factory_logo.url}}" alt="logo" class="img-circle"
            style="width: 80px; height: 80px; margin-right:10px; float: left;">
          <a href="{%url 'transactions:view_factory' factory.pk%}" class="white">{{factory.factory_name}}</a>
          <div class="dark">
            <i class="lnr lnr-map-marker"></i>
            <span>{{factory.country}}</span>|
            <span>{{factory.region}}</span><br>
          </div>
          <span>
            {%if factory.rating == 0%}
            <i class="lnr lnr-star-half" style="color: orange;"></i>
            {%elif factory.rating == 1%}
            <i class="lnr lnr-star-half" style="color: orange;"></i>
            <i class="lnr lnr-star-half" style="color: orange;"></i>
            {%elif factory.rating == 2%}
            <i class="lnr lnr-star-half" style="color: orange;"></i>
            <i class="lnr lnr-star-half" style="color: orange;"></i>
            <i class="lnr lnr-star-half" style="color: orange;"></i>
            {%else%}
            rating: <i class="lnr lnr-star" style="color: orange;"></i><i class="lnr lnr-star"
              style="color: orange;"></i><i class="lnr lnr-star" style="color: orange;"></i><i class="lnr lnr-star"
              style="color: orange;"></i><i class="lnr lnr-star" style="color: orange;"></i>
            {%endif%}
          </span>
        </div><br>
        {%endfor%}
        <div class="tooltip arrow fade dark" id="tool" style="left: 18%;">
          <p style="font-size: 150%;">A list of all factories</p>
        </div>
        <script>
          function showTooltip(e)
          {
            document.getElementById('tool').classList.add('show')
          }
          function hideTooltip(e)
          {
            document.getElementById('tool').classList.remove('show')
          }
        </script>
        <a href="{% url 'accounts:factories'%}" class="btn btn-outline-success" onmouseover="showTooltip(this)"
          onmouseout="hideTooltip(this)">Show All
          factories</a>
      </div>
      <div class="panel-body orange-border ftco-animate">
        <div class="panel-heading">
          <h3 class="orange livetext-mega">Recent Transactions</h3>
          <div class="right">
            </button>
          </div>
        </div>
        {%if ordersmade == 0%}
        {%else%}
        <div class="panel-body no-padding"
          style="overflow: scroll; overflow-y: hidden; overflow-wrap: break-word; overflow-x:auto;">
          <table class="table-sm table-hover">
            <thead>
              <tr style="text-align: center;">
                <th class="small">Order No.</th>
                <th class="small">Name</th>
                <th class="small">Amount</th>
                <th class="small">Date &amp; Time</th>
                <th class="small">Status</th>
                <th class="small">Transaction Validity</th>
                <th class="small">Transaction Hash</th>
                <th class="small">Coffee Type</th>
              </tr>
            </thead>
            <tbody style="text-align: center;">
              {% for order in order_queryset %}
              <tr>
                <td><a href="/transactions/view_order/{{order.id}}/">{{order.id}}</a></td>
                <td>{{order.employee.factory.factory_name}}</td>
                <td>{{order.amount}} tonnes</td>
                <td>{{order.date_placed}}</td>
                {% if order.status == 0 %}
                <td class="small"><span class="label label-warning">Pending</span>
                </td>
                {% elif order.status == 1 %}
                <td class="small"><span class="label label-success">Accepted</span></td>
                {% elif order.status == 2 %}
                <td class="small"><span class="label label-success">Processed</span></td>
                {% elif order.status == 3 %}
                <td class="small"><span class="label label-success">Completed</span></td>
                {% endif %}
                {%if order.chain_valid%}
                <td class="small">
                  <span class="label-success label">Trusted</span>
                </td>
                {%else%}
                <td class="small">
                  <span class="label-error label">Suspicius</span>
                </td>
                {%endif%}

                <td>
                  <small class="no-padding no-margin">{{order.order_hash}}</small>
                </td>
                <td>
                  <small class="no-padding no-margin">{{order.auction.coffee_type}}</small>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {%endif%}
        <div class="panel-body dark">
          <div class="row">
            <div class="col-md-6">
              {%if ordersmade == 0%}
              <span class="panel-note"><i class="fa fa-clock-o"></i> No orders, new orders will be listed here</span>
              <br>
              <span><a href="/help">Show me how to make an order</a></span>
              {%else%}
              <span class="panel-note"><i class="fa fa-clock-o"></i> Last 24 hours</span>
              {%endif%}
            </div>
          </div>
        </div>
      </div>
      <div class="panel-body orange-border ftco-animate">
        <div class="panel-body">
          <h1 class="orange livetext-mega">Coffee Prices</h1>
          <h3 class="white">${{MeanPrice}} Per Tonne</h3>
          <p>Coffee prices in the market</p>
          <canvas id="prices" height="100%"></canvas>
        </div>
      </div><br>
      <div class="row">
        <div class="col-md-12">
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <!-- RECENT PURCHASES -->

          <!-- END RECENT PURCHASES -->

        </div>
      </div><br> <br>
      <div class="panel-body orange-border ftco-animate">
        <h4 class="orange livetext-mega">Orders Placed</h4>
        <div class="panel-body"><span class="white title">{{orders}} order{{orders|pluralize}}</span><br></div>
        <hr>
        <div class="dark-l panel-body"><span class="white"><i class="lnr lnr-hourglass"
              style="font-size: 140%; color: orange;"></i> {{pending}} pending</span><br></div><br>
        <div class="dark-l panel-body"><span class="white"><i class="lnr lnr-checkmark-circle"
              style="font-size: 140%; color: rgb(30, 255, 0);"></i> {{confirmed}} Accepted</span><br></div><br>
        <div class="dark-l panel-body"><span class="white">
            <i class="lnr lnr-car" style="font-size: 140%; color: rgb(45, 155, 219);"></i> {{processed}}
            on ship</span><br></div><br>
        <div class="dark-l panel-body"><span class="white">
            <i class="lnr lnr-gift" style="font-size: 140%; color: orange;"></i>
            <span>
              {{completed}}
              Completed
            </span>
        </div>
      </div><br>
      <div class="metric ftco-animate">
        <h4 class="white">Actions</h4>
        <a href="{%url 'transactions:showtransactions' user%}" class="a">View all Transactions</a><br>
        <a href="{%url 'transactions:shownotifications' user.username%}" class="a">Notifications</a>
        <hr>
        <h4 class="white">Common</h4>
        <a href="#" class="a">Print Transaction report</a><br>
        <a href="{%url 'transactions:track_orders' user.username%}" class="a">Trace order</a><br>
        <a href="/blog" class="a">Blog</a><br>
        <a href="{%url 'feedback:showfeedback'%}" class="a">Feedback</a>
      </div>
    </div>
    <br>

    <!-- END OVERVIEW -->
  </div>
</div>
</div>
</div>
<!-- END MAIN CONTENT -->
</div>
{% endblock content %}
{% block js %}
<script src="{%static 'node_modules/chart.js/dist/Chart.js'%}"></script>
<script>
  months = []
  prices = []
  factories = []
  amounts = []
</script>
{%for month in months_price%}
<script>
  included = false
  months.forEach(element =>
  {
    if (element === "{{month}}")
    {
      included = true
    }
  });
  if (!included)
  {

    months.push("{{month}}")
  }
  n = months.length - 1
  newmonths = []
  console.log(n)
  while (n >= 4)
  {
    newmonths.push(months[n])
    n = n - 1
    console.log(n)
    months = newmonths
  }

</script>

{%endfor%}
{%for price in prices%}
<script>
  prices.push("{{price}}")
</script>
{%endfor%}
<script src="{% static 'toastr/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'toastr/toastr.min.js' %}"></script>
<script>
  n = prices.length - 1
  newprices = []
  console.log(prices)
  while (n >= 4)
  {
    newprices.push(prices[n])
    console.log(newprices)
    n = n - 1
    prices = newprices
  }

  var notificationSocket = new WebSocket(
    "ws://" + window.location.host + "/ws/transactions/notifications/{{user.id}}/"
  );
  notificationSocket.onmessage = function (e)
  {
    var receivedMessage = JSON.parse(e.data);

    toastr.options = {
      "closeButton": true,
      "debug": false,
      "newestOnTop": false,
      "progressBar": false,
      "positionClass": "toast-top-right",
      "preventDuplicates": false,
      "onclick": null,
      "showDuration": "300",
      "hideDuration": "1000",
      "timeOut": "5000",
      "extendedTimeOut": "1000",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
    }

    toastr["info"](receivedMessage['content'], "new message received from " + receivedMessage['username'] +
      ' order number ' + receivedMessage['order_id'])

  }

  var ctx = document.getElementById('prices').getContext('2d');
  months.push("")
  var myChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: months,
      pointRadius: 0,
      borderWidth: 1,
      datasets: [{
        label: 'Price line in real time',
        data: prices,
        backgroundColor: [
          'rgba(100,100,100,0.2)',
        ],
        borderColor: [
          'rgba(226, 109, 6, 1)'
        ],
        borderWidth: 3
      }

      ]
    },
    options: {
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: false
          }
        }]
      }
    }
  });
</script>
{% endblock js %}

accounts/templates/factories.html
{% extends 'base.html' %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'toastr/toastr.min.css' %}">
{% endblock style %}
{% block content %} {% load static %}
<div class="main">
    <div class="main-content ">
        <div class="container-fluid">
            <div class="panel-body">
                <span class="orange title">CoffeeAfrica|</span><span class="blue">Partners</span><br><br>
                {%for factory in factories%}
                <div class="panel-body orange-border ftco-animate">
                    <img src="{{factory.factory_logo.url}}" alt="logo" class="img-circle"
                        style="width: 80px; height: 80px; margin-right:10px; float: left;">
                    <a href="{%url 'transactions:view_factory' factory.pk%}"
                        class="white title livetext">{{factory.factory_name}}</a>
                    <div class="dark">
                        <span>{{factory.country}}</span>|
                        <span>{{factory.region}}</span><br>
                    </div>
                    <span>
                        {%if factory.rating == 0%}
                        <i class="lnr lnr-star-half" style="color: orange;"></i>
                        {%elif factory.rating == 1%}
                        <i class="lnr lnr-star-half" style="color: orange;"></i>
                        <i class="lnr lnr-star-half" style="color: orange;"></i>
                        {%elif factory.rating == 2%}
                        <i class="lnr lnr-star-half" style="color: orange;"></i>
                        <i class="lnr lnr-star-half" style="color: orange;"></i>
                        <i class="lnr lnr-star-half" style="color: orange;"></i>
                        {%else%}
                        rating: <i class="lnr lnr-star" style="color: orange;"></i><i class="lnr lnr-star"
                            style="color: orange;"></i><i class="lnr lnr-star" style="color: orange;"></i><i
                            class="lnr lnr-star" style="color: orange;"></i><i class="lnr lnr-star"
                            style="color: orange;"></i>
                        {%endif%}
                    </span><br>
                    <span>Partner since {{factory.date_created}}</span>
                    <hr>
                    <span class="white">About Factory</span><br>
                    <span>{{factory.factory_bio}}</span><br>
                    <a href="#">Send Message</a>
                    <br>
                    <a href="#">Report</a>
                </div><br>
                {%endfor%}
            </div>
        </div>
    </div>
</div>
{%endblock content%}