accounts/urls.py
from django.urls import path
from .views import (
    homepage,
    profile,
    login,
    create_account,
    dashboard,
    GetFactoriesView,
    accounts,
    create_buyer_account,
    about,
    contact,
    services,
    create_factory_account,
    market,
    help,
)

namespace = "accounts"

urlpatterns = [
    path("", homepage, name="homepage"),
    path("profile/", profile, name="profile"),
    path("login/", login, name="login"),
    path("create_account/", create_account, name="create_account"),
    path("dashboard/", dashboard, name="dashboard"),
    path("factories/", GetFactoriesView.as_view(), name="factories"),
    path("GetSarted/", accounts, name="start"),
    path("Buyer/", create_buyer_account, name="buyer"),
    path("about/", about, name="about"),
    path("contact/", contact, name="contact"),
    path("services/", services, name="services"),
    path("Factory/", create_factory_account, name="factory"),
    path("market/", market, name="market"),
    path("help/", help, name="help"),
]

agriproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

namespace = "transactions"

urlpatterns = [
    path("dev/", admin.site.urls),
    path("", include(("accounts.urls", "accounts"), namespace="accounts")),
    path(
        "transactions/",
        include(("transactions.urls", "transactions"), namespace="transactions"),
    ),
    path("feedback/", include(("feedback.urls", "feedback"), namespace="feedback")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path
from .views import (
    add_auction,
    view_market,
    view_market_id,
    view_order,
    view_auction,
    chat,
    view_factory,
    AcceptOrderView,
    EnterShipmentInfoView,
    AddShipmentAddressView,
    GetChartView,
    confirmArival,
    DeletAuction,
    CreateAuction,
    GetBuyerChartView,
    ShowAuctionHistory,
    ShowTransactions,
    ShowNotifications,
    TrackOrder,
    CreateOrder,
)

namespace = "transactions"

urlpatterns = [
    path("add_auction/<str:factory_name>/", add_auction, name="add_auction"),
    path("view_market/", view_market, name="view_market"),
    path("view_market/<int:id>/", view_market_id, name="view_market"),
    path("view_order/<int:order_id>/", view_order, name="view_order"),
    path("view_auction/", view_auction, name="view_auction"),
    path("chat/", chat, name="chat"),
    path(
        "view_market/view_factory/<int:factory_id>/", view_factory, name="view_factory"
    ),
    path(
        "view_order/<int:factory_id>/update_order/",
        AcceptOrderView.as_view(),
        name="accept_order",
    ),
    path(
        "shipmentinfo/<int:order_id>/",
        EnterShipmentInfoView.as_view(),
        name="shipmentview",
    ),
    path("ShipmentSaved/", EnterShipmentInfoView.as_view(), name="saveshipment"),
    path(
        "ShipmentAddress/",
        AddShipmentAddressView.as_view(),
        name="addshippmentaddress",
    ),
    path("charts/<str:factory_name>", GetChartView.as_view(), name="charts"),
    path("bcharts/<str:buyer_name>", GetBuyerChartView.as_view(), name="bcharts"),
    path("order-arrived/<int:order_id>", confirmArival, name="confirm"),
    path(
        "auction-remove/<int:auction_id>", DeletAuction.as_view(), name="delete-auction"
    ),
    path("create_auction/", CreateAuction.as_view(), name="create_auction"),
    path(
        "auction_history/<str:factory_name>/",
        ShowAuctionHistory.as_view(),
        name="auction_history",
    ),
    path("<str:factory_name>/", ShowTransactions.as_view(), name="showtransactions",),
    path(
        "notifications/<str:name>/",
        ShowNotifications.as_view(),
        name="shownotifications",
    ),
    path("orders/<str:user_name>/", TrackOrder.as_view(), name="track_orders"),
    path("order/create/", CreateOrder.as_view(), name="order"),
]

transactions/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect
from .models import Auction, Order, Chat, AdminMessage
from backup.models import BackAuction, BackOrder
from backup import backup_utils
import calendar
import dateutil
from . import calenderutil

try:
    from ..blockSys import intergrator
except:
    from blockSys import intergrator, utils
import django
from accounts.models import SellerFactory
from accounts.models import SellerFactoryEmployee
from accounts.models import Buyer
from blockSys import *
from hashlib import sha256
from . import forms
from django.views.generic import View
from django.contrib.auth.models import User
import datetime
import time
from .forms import CreateAuctionForm
import json

from django.template.loader import get_template
import numpy as np


def add_auction(request, factory_name):
    form = CreateAuctionForm()
    try:
        auction = Auction.objects.get(
            factory=SellerFactory.objects.get(factory_name=factory_name)
        )
    except:
        auction = None
    return render(
        request, "add_auction.html", context={"form": form, "auction": auction}
    )


def confirmArival(request, order_id):
    print(request.GET.keys())
    order = Order.objects.get(pk=order_id)
    order.arrived = True
    order.status = 3
    order.when_arrived = datetime.date.today()
    chain = intergrator.ReadChainFromFile(order_id)
    chain.addTochain(order)

    order.chain = chain.blockchain.getChainList()
    hasher = sha256(str(order.chain).encode("utf-8"))

    order.hash = hasher.hexdigest()
    order.chain_valid = chain.CheckValidity()
    order.save()
    chain.DumpChain(order_id)
    backup_utils.BackOrder(order)
    if order.last_order:
        order.auction.delete()
    return HttpResponse("Updated")


class GetBuyerChartView(View):
    def get(self, request, buyer_name, *args, **kwargs):
        print(buyer_name)
        try:
            buyer = Buyer.objects.get(user=User.objects.get(username=buyer_name))
            auctions = BackAuction.objects.all()
            prices = []
            months_price = []
            months = []
            for auction in auctions:
                price = auction.price_per_tonne
                months_price.append(auction.date)
                prices.append(price)
            sumprice = sum(prices)
            months = calenderutil.getAllMonthsStr()
            mean_price = sumprice / len(prices)
            context = {
                "prices": prices,
                "months_price": months_price,
                "months": months,
                "MeanPrice": round(mean_price, 3),
            }

            factories_traded = []
            amount = []
            amts = {}
            orders = BackOrder.objects.filter(buyer=buyer)
            for order in orders:
                factory = order.employee.factory
                if factory not in factories_traded:
                    factories_traded.append(factory)
                if amts.get(factory.factory_name):
                    amts[factory.factory_name] = (
                        order.amount + amts[factory.factory_name]
                    )
                else:
                    amts[factory.factory_name] = order.amount

            for x in range(len(factories_traded)):
                amount.append(amts.get(factories_traded[x].factory_name))

            context["factories"] = factories_traded
            print(amount)
            context["amounts"] = amount

            return render(request, "buyer_charts.html", context)
        except:
            auctions = Auction.objects.all()
            prices = []
            months_price = []
            months = []
            for auction in auctions:
                price = auction.price_per_tonne
                months_price.append(auction.date)
                prices.append(price)
            sumprice = sum(prices)
            print(prices)
            months = calenderutil.getAllMonthsStr()
            try:
                mean_price = sumprice / len(prices)
            except:
                mean_price = 0
            context = {
                "prices": prices,
                "months_price": months_price,
                "months": months,
                "MeanPrice": round(mean_price, 3),
            }

            return render(request, "buyer_charts.html", context)


class GetChartView(View):
    def get(self, request, factory_name):
        factory = SellerFactory.objects.get(factory_name=factory_name)

        class Stat:
            def __init__(self, data, year=2019):
                self.data = data
                self.year = year

        orders = BackOrder.objects.all()
        data = {
            "jan": 0,
            "feb": 0,
            "mar": 0,
            "apr": 0,
            "may": 0,
            "jun": 0,
            "jul": 0,
            "aug": 0,
            "sep": 0,
            "oct": 0,
            "nov": 0,
            "dec": 0,
        }
        processed_orders = 0
        received = 0
        total_tonnes = 0
        tones_sold = 0

        auctions = BackAuction.objects.all()
        for auction in auctions:
            if auction.factory == factory:
                total_tonnes += auction.tonnes
                tones_sold += auction.tonnes - auction.tonnes_left

        for order in orders:
            if order.auction.factory == factory:
                if order.status == 2 or order.status == 3:
                    processed_orders += 1
                if order.auction.factory == factory:
                    received += 1
                if order.arrived:
                    if order.date_placed.year == datetime.date.today().year:
                        if order.date_placed.month == 1:
                            data["jan"] += order.amount
                        elif order.date_placed.month == 2:
                            data["feb"] += order.amount
                        elif order.date_placed.month == 3:
                            data["mar"] += order.amount
                        elif order.date_placed.month == 4:
                            data["apr"] += order.amount
                        elif order.date_placed.month == 5:
                            data["may"] += order.amount
                        elif order.date_placed.month == 6:
                            data["jun"] += order.amount
                        elif order.date_placed.month == 7:
                            data["jul"] += order.amount
                        elif order.date_placed.month == 8:
                            data["aug"] += order.amount
                        elif order.date_placed.month == 9:
                            data["sep"] += order.amount
                        elif order.date_placed.month == 10:
                            data["oct"] += order.amount
                        elif order.date_placed.month == 12:
                            data["nov"] += order.amount
                        elif order.date_placed.month == 12:
                            data["dec"] += order.amount

        value_increase = 0
        if datetime.date.today().month == 1:
            val = data.get("jan")
            value_increase = val
        elif datetime.date.today().month == 2:
            val = data.get("feb")
            value_increase = val - data.get("jan")
        elif datetime.date.today().month == 3:
            val = data.get("mar")
            value_increase = val - data.get("feb")
        elif datetime.date.today().month == 4:
            val = data.get("apr")
            value_increase = val - data.get("mar")
        elif datetime.date.today().month == 5:
            val = data.get("may")
            value_increase = val - data.get("apr")
        elif datetime.date.today().month == 6:
            val = data.get("jun")
            value_increase = val - data.get("may")
        elif datetime.date.today().month == 7:
            val = data.get("jul")
            value_increase = val - data.get("jun")
        elif datetime.date.today().month == 8:
            val = data.get("aug")
            value_increase = val - data.get("jun")
        elif datetime.date.today().month == 9:
            val = data.get("sep")
            value_increase = val - data.get("aug")
        elif datetime.date.today().month == 10:
            val = data.get("oct")
            value_increase = val - data.get("sep")
        elif datetime.date.today().month == 12:
            val = data.get("nov")
            value_increase = val - data.get("oct")
        elif datetime.date.today().month == 12:
            val = data.get("dec")
            value_increase = val - data.get("nov")

        stat = Stat(data, datetime.date.today().year)
        context = {}
        context["stat"] = stat
        context["processed"] = processed_orders
        context["recieved"] = received
        context["total_tonnes"] = total_tonnes
        context["tonnes_sold"] = tones_sold

        if value_increase < 0:
            value_increase = str(value_increase)
        elif value_increase == 0:
            value_increase = str(value_increase)
        else:
            value_increase = "+" + str(value_increase)

        context["value_increase"] = value_increase

        percentage_sold = 0.00
        if total_tonnes != 0:
            percentage_sold = (tones_sold * 100) / total_tonnes

        context["percentage_sold"] = round(percentage_sold, 2)

        return render(request, "factory_charts.html", context)


class AcceptOrderView(View):
    def post(self, request, factory_id):
        id = request.POST.get("id")
        order = Order.objects.get(pk=id)
        order.status = 1
        chain = intergrator.ReadChainFromFile(id)
        chain.addTochain(order)
        order.order_valid = chain.CheckValidity()
        order.chain = chain.blockchain.getChainList()
        chain.DumpChain(id)
        myhasher = sha256(str(order.chain).encode("utf-8"))
        order.hash = myhasher.hexdigest()

transactions/templates/add_auction.html
{% extends 'base.html' %} {% block content %}
<script>
  showLoading()
</script>
<div class="main">
  <!-- MAIN CONTENT -->
  <div class="main-content">
    <div class="container-fluid">
      {%if error%}
      <div class="dark-l panel-body">
        <h4 class="orange">An Error Occured</h4>
        <p>{{error}}</p>
      </div>
      {%endif%}
      <div class="text-center">
        <img src="{{user.sellerfactoryemployee.factory.factory_logo.url}}" alt=""
          style="height: 180px; border-radius: 90px; box-shadow: -.1em -.1em 2em .1em rgba(255, 255, 255, 0.486);">
        <h2 style="font-size: 150%;">{{user.sellerfactoryemployee.factory}}</h2>
        <span>{{user.sellerfactoryemployee.factory.factory_initials}}</span>
        <hr style="background-color: rgba(255, 255, 255, 0.486);">
      </div>
      {%if auction%}
      <div class="panel-body text-center col-lg-12">
        <i class="lnr lnr-warning" style="font-size:250%; color: red;"></i>
        <h2 class="orange">You already have an on going Auction</h2>
        <span class="subheading">Please note, you CANNOT have more than one auction in the market at a time,
          <p>
            if
            you must
            create a new one
            try deleting the on-going auction and try again</p>
        </span>
        <br>
        <a href="/transactions/view_auction" class="btn btn-outline-warning px-4 py-3">Show Current Auction</a>
        <a href="/dashboard" class="btn btn-outline-success px-4 py-3">Back to Dashboard</a>
      </div>
      {%else%}
      <span>Fill this form to create a new auction</span>
      <form method="POST" class="dark-l panel-body col-lg-12 pl-md-5 ftco-animate billing-form p-3 p-md-5"
        action="{%url 'transactions:create_auction'%}">
        {% csrf_token %}
        <input type="hidden" name="factory" id="factory" value="{{user.sellerfactoryemployee.factory.pk}}">
        <input type="hidden" name="employee" id="employee" value="{{user.sellerfactoryemployee.pk}}">
        {%for field in form%}
        <div class="form-group">
          <label class="" style="color: orange;">{{field.label}}</label><br>
          {{field}}
        </div>
        {%endfor%}
        <input type="date" class="form-control" name="date_harvested" id="date_harvested">

        <a href="#" class="blue">Read Our Terms of service</a><br>
        <button type="submit" class="btn btn-outline-warning py-3 px-4 btn-lg">Add to market</button>
      </form>
      {%endif%}
    </div>
    <!-- </form> -->
  </div>
</div>
</div>
{% endblock content %} {% block js %}
<script>
  // var auctionSocket = new WebSocket(
  //   "ws://" + window.location.host + "/ws/transactions/addauction/"
  // );
  // auctionSocket.onmessage = function(e) {
  //   console.log(JSON.parse(e.data));
  // };
  // auctionSocket.onclose = function(e) {
  //   console.log("chat socket disconnected unexpectedly");
  // };
  // document.querySelector("#submit_button").onclick = function(e) {
  //   var pricePerTonne = document.querySelector("#price_per_tonne").value;
  //   var dateHarvested = document.querySelector("#date_harvested").value;
  //   var amountInTonnes = document.querySelector("#amount_in_tonnes").value;
  //   auctionSocket.send(
  //     JSON.stringify({
  //       pricePerTonne: pricePerTonne,
  //       dateHarvested: dateHarvested,
  //       amountInTonnes: amountInTonnes
  //     })
  //   );
  // };
</script>
{% endblock js %}

transactions/templates/auction_history.html
{% extends 'base.html' %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'toastr/toastr.min.css' %}">
{% endblock style %}
{% block content %} {% load static %}
<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid" style="background-color: transparent;">
            {%if not auctions%}
            <div class="col-lg-12 text-center" style="background-color: rgba(0, 0, 0, 0);">
                <h3 class="orange">No Auction History</h3>
                <span><i class="lnr lnr-history" style="font-size: 260%;"></i></span><br>
                <span>You have no auction history, you can start one over at the dashboard</span><br>
                <a href="/transactions/add_auction/{{user.sellerfactoryemployee.factory}}/"
                    class="btn btn-outline-success">Create a new auction</a>
            </div>
            {%endif%}
            {%for auction in auctions%}

            <div class="dark-l">
                <div class="metric">
                    <h2>
                        Index no: {{auction.pk}}
                    </h2>
                    <hr>
                    {{auction.coffee_type}} <br>
                    {{auction.tonnes}} tonne{{auction.tonnes | pluralize}} <br>
                    Auctioned by {{auction.employee}} on {{auction.date}} <br>
                </div>
            </div>
            {%endfor%}

        </div>
    </div>
</div>
{%endblock content%}

transactions/templates/buy_bundle.html
{% extends 'base.html' %} {% block content %}
<div class="main">
  <!-- MAIN CONTENT -->
  <div class="main-content">
    <div class="container-fluid">
      <section class="">
        <div class="container">
          <div class="row">
            <div class="col-lg-5 mb-5 ftco-animate img img-half" style="padding-top: 0%;">
              <a href="{{auction.factory.factory_logo.url}}" class="image-popup"><img
                  src="{{auction.factory.factory_logo.url}}" class="img-fluid" alt="Colorlib Template"></a>
            </div>
            <div class="col-lg-6 pl-md-5 ftco-animate billing-form p-3 p-md-5"
              style="background-color: rgba(0, 0, 0, 0.521);">
              <h3 class="orange title">{{auction.coffee_type}} coffee</h3>
              <p class="price"><span>${{auction.price_per_tonne}} per tonne</span></p>
              {{auction.tonnes_left}} Tonnes left @
              <span>Tempreture {{auction.tempreture}}&deg; | Humidity {{auction.humidity}}%</span>
              <p>{{auction.description}}</p>
              <form class="row mt-2" method="POST" action="{%url 'transactions:order'%}">
                <div class="col-md-12">
                  {%csrf_token%}
                  <input type="hidden" value="{{user.buyer.pk}}" name="buyer">
                  <input type="hidden" value="{{auction.id}}" name="auction">
                  <input type="hidden" value="{{auction.employee.pk}}" name="employee">
                  <div class="form-group slide-left-input">
                    <label for="amount" class="orange">Amount in Tonnes</label><br>
                    <small id="amounthelp" class="form-text text-muted blue">Enter how many tonnes of coffee you want to
                      buy
                      from
                      this
                      bundle.</small>
                    <input id="tonnes" type="number" class="form-control" aria-describedby="emailHelp" name="tonnes" />
                  </div>
                  <div class="form-group slide-left-input">
                    <label for="date" class="orange">Prefered Date of shipment</label><br>
                    <small id="datehelp" class="form-text text-muted">what is your prefered shipment date for the
                      coffee</small>
                    <input type="date" class="form-control" id="shipmentdate" aria-describedby="emailHelp"
                      name="date" />

                  </div>
                  <div class="form-group slide-left-input">
                    <label for="exampleInputPassword1">Confirm your account Password</label>
                    <input id="password" type="password" class="form-control" id="exampleInputPassword1"
                      name="password" />
                  </div>
                  <button class="btn btn-outline-success py-3 px-5" type="submit">Place Order</button>
                  <br>
                  <br>
                </div>
              </form>
            </div>
          </div>
      </section>
    </div>
  </div>
</div>
{% endblock content %} {% block js %}
<script>
  // var addOrderSocket = new WebSocket(
  //   "ws://" +
  //   window.location.host +
  //   "/ws/transactions/addorder/{{auction.employee.user.id}}/"
  // );
  // document.querySelector("#placeorder").onclick = function (e)
  // {
  //   addOrderSocket.send(
  //     JSON.stringify({
  //       user: "{{auction.employee.pk}}",
  //       auction: "{{auction.id}}",
  //       shipmentdate: document.querySelector("#shipmentdate").value,
  //       tonnes: document.querySelector("#tonnes").value,
  //       password: document.querySelector("#password").value
  //     })
  //   );
  //   location.replace('/dashboard')

  //   addOrderSocket.onmessage = function (e)
  //   {
  //     console.log(JSON.parse(e.data));
  //   };
  //   addOrderSocket.onclose = function (e)
  //   {
  //     console.log("the addOrderSocket socket closed unexpectedly");
  //   };
  // };
</script>
{% endblock js %}

transactions/templates/confirm_password.html
{% extends 'base.html' %} {% block content %}{% load static %}
<div class="main">
  <!-- MAIN CONTENT -->
  <div class="main-content">
    <div class="container-fluid">
      <div id="wrapper">
        <div class="vertical-align-wrap">
          <div class="vertical-align-middle">
            <div class="auth-box lockscreen clearfix">
              <div class="content">
                <h1 class="sr-only">Klorofil - Free Bootstrap dashboard</h1>
                <div class="logo text-center">
                  <img
                    src="{% static 'assets/img/logo-dark.png' %}"
                    alt="Klorofil Logo"
                  />
                </div>
                <div class="user text-center">
                  <img
                    src="{% static 'assets/img/user-medium.png' %}"
                    class="img-circle"
                    alt="Avatar"
                  />
                  <h2 class="name">Samuel Gold</h2>
                </div>
                <form method="POST">
                  {% csrf_token %}
                  <div class="input-group">
                    <input
                      type="password"
                      class="form-control"
                      placeholder="confirm your password ..."
                      name="pass"
                    />
                    <span class="input-group-btn"
                      ><button type="submit" class="btn btn-primary">
                        <i class="fa fa-arrow-right"></i></button
                    ></span>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

transactions/templates/shipmentForm.html
{% extends "base.html" %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
<link rel="stylesheet" href="{% static 'chat/style.css' %}" />
{% endblock style %}
{% block content %}

<script>
    hideLoading()
</script>
<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid">
            <div class="dark-l panel-body orange-border">
                #{{order.id}} | Buyer: {{order.buyer}}<br>
                {%if order.chain_valid%}
                <span class="label-success label">Trusted Transaction</span><br>
                {%else%}
                <br><span class="label-error label>Order has been verified</span><br>
                {%endif%}

                units requested: {{order.amount}} tonne{{order.amount | pluralize}}<br><br>
                <span>Client expects Shipment by: </span><br><span class=" mx-sm-3">{{order.expected_date}}</span>
                <br><a href="#">Raise Issue</a>
            </div><br>
            <div class="dark-l panel-body orange-border">
                <p class="title orange livetext">Enter Shipment information</p>
                <small class="passwordHelpBlock">Enter valid shipment details. These Details will be
                    validated</small>
                <br>
                <br>
                <form action="{%url 'transactions:saveshipment'%}" method="POST">
                    {%csrf_token%}
                    <input type="hidden" name="id" id="id" value="{{order.pk}}">
                    {%for field in form%}
                    <div class="form-group">
                        {{field}}
                        {%if field.help_text%}
                        <small class="passwordHelpBlock">{{field.helpText}}</small>
                        {%endif%}
                    </div>
                    {%endfor%}
                    <button type="submit" class="btn btn-outline-primary">Publish information</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

transactions/templates/view_factory.html
{% extends 'base.html' %} {% block content %} {% load static %}
<script>
  hideLoading()
</script>
<link rel="stylesheet" href="{%static 'assets/CSS/mine.css'%}">
<div class="main">
  <!-- MAIN CONTENT -->
  <div class="main-content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6">
          <div class="dark-l panel-body orange-border">
            <img style=" width: 60px; height: 60px; margin-right:10px; float: left;" src="{{factory.factory_logo.url}}"
              class="img-circle" />
            <div class="media-body">
              <h5 class="panel-title">
                <h4 style="margin: 0px"><b class="orange livetext">{{factory.factory_name}}</b></h4>
                <br />
                Since {{factory.date_created}}<br />
                Altitude 20 |Temperature 30
              </h5>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="dark-l panel-body orange-border">
            <h4><b class="livetext orange">auction information</b></h4>
            {% for auction in auctions%}
            <div class="dark panel-body">
              <span class="title orange">Ongoing Auction</span><br>
              <span>Auction No. {{auction.pk}}</span><br>
              <span>Tonnes {{auction.tonnes}}</span><br>
              <span>${{auction.price_per_tonne}} per tonne</span><br>
              <span>{{auction.coffee_type}}</span><br>
              <span>{{auction.tonnes_left}} tonne{{auction.tonnes_left|pluralize}} Left</span><br>
              <a href="{%url 'transactions:view_market' auction.pk%}">Buy Form this Auction</a>
            </div>
            {%endfor%}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="dark-l panel-body orange-border">
            <h4><b class="orange livetext">Legal documentation</b><br />
              {%if factory.trade_license%}
              <h3>Trade License</h3>
              <a href="{{factory.trade_license.url}}">Download Copy of license</a>
              <br><span>Content Validated</span>
              {%else%}
              <span>NO LICENSE</span>
              {%endif%}
          </div>
          <div class="dark-l panel-body orange-border">
            <h4><b class="orange livetext">Factory Bio</b></h4>
            <p style="align-items: left;">
              <div>
                <span class="text">
                  {{factory.factory_bio}}
                </span>
              </div>
            </p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="dark-l panel-body orange-border">

            <h4 class="orange livetext">Map</h4>
            {{factory.googlemap|safe}}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}