accounts/urls.py
from django.urls import path
from .views import (
    homepage,
    profile,
    login,
    create_account,
    dashboard,
    GetFactoriesView,
    accounts,
    create_buyer_account,
    about,
    contact,
    services,
    create_factory_account,
    market,
    help,
)

namespace = "accounts"

urlpatterns = [
    path("", homepage, name="homepage"),
    path("profile/", profile, name="profile"),
    path("login/", login, name="login"),
    path("create_account/", create_account, name="create_account"),
    path("dashboard/", dashboard, name="dashboard"),
    path("factories/", GetFactoriesView.as_view(), name="factories"),
    path("GetSarted/", accounts, name="start"),
    path("Buyer/", create_buyer_account, name="buyer"),
    path("about/", about, name="about"),
    path("contact/", contact, name="contact"),
    path("services/", services, name="services"),
    path("Factory/", create_factory_account, name="factory"),
    path("market/", market, name="market"),
    path("help/", help, name="help"),
]

agriproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

namespace = "transactions"

urlpatterns = [
    path("dev/", admin.site.urls),
    path("", include(("accounts.urls", "accounts"), namespace="accounts")),
    path(
        "transactions/",
        include(("transactions.urls", "transactions"), namespace="transactions"),
    ),
    path("feedback/", include(("feedback.urls", "feedback"), namespace="feedback")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/urls.py
from django.urls import path
from .views import CreateEscalation, CreateRawFeedBack, MainFeedBackView

app_name = "feedback"

urlpatterns = [
    path("", CreateRawFeedBack.as_view(), name="createfeedback"),
    path("<int:order_id>/", CreateEscalation.as_view(), name="createescalation"),
    path("main/", MainFeedBackView.as_view(), name="showfeedback"),
]

transactions/urls.py
from django.urls import path
from .views import (
    add_auction,
    view_market,
    view_market_id,
    view_order,
    view_auction,
    chat,
    view_factory,
    AcceptOrderView,
    EnterShipmentInfoView,
    AddShipmentAddressView,
    GetChartView,
    confirmArival,
    DeletAuction,
    CreateAuction,
    GetBuyerChartView,
    ShowAuctionHistory,
    ShowTransactions,
    ShowNotifications,
    TrackOrder,
    CreateOrder,
)

namespace = "transactions"

urlpatterns = [
    path("add_auction/<str:factory_name>/", add_auction, name="add_auction"),
    path("view_market/", view_market, name="view_market"),
    path("view_market/<int:id>/", view_market_id, name="view_market"),
    path("view_order/<int:order_id>/", view_order, name="view_order"),
    path("view_auction/", view_auction, name="view_auction"),
    path("chat/", chat, name="chat"),
    path(
        "view_market/view_factory/<int:factory_id>/", view_factory, name="view_factory"
    ),
    path(
        "view_order/<int:factory_id>/update_order/",
        AcceptOrderView.as_view(),
        name="accept_order",
    ),
    path(
        "shipmentinfo/<int:order_id>/",
        EnterShipmentInfoView.as_view(),
        name="shipmentview",
    ),
    path("ShipmentSaved/", EnterShipmentInfoView.as_view(), name="saveshipment"),
    path(
        "ShipmentAddress/",
        AddShipmentAddressView.as_view(),
        name="addshippmentaddress",
    ),
    path("charts/<str:factory_name>", GetChartView.as_view(), name="charts"),
    path("bcharts/<str:buyer_name>", GetBuyerChartView.as_view(), name="bcharts"),
    path("order-arrived/<int:order_id>", confirmArival, name="confirm"),
    path(
        "auction-remove/<int:auction_id>", DeletAuction.as_view(), name="delete-auction"
    ),
    path("create_auction/", CreateAuction.as_view(), name="create_auction"),
    path(
        "auction_history/<str:factory_name>/",
        ShowAuctionHistory.as_view(),
        name="auction_history",
    ),
    path("<str:factory_name>/", ShowTransactions.as_view(), name="showtransactions",),
    path(
        "notifications/<str:name>/",
        ShowNotifications.as_view(),
        name="shownotifications",
    ),
    path("orders/<str:user_name>/", TrackOrder.as_view(), name="track_orders"),
    path("order/create/", CreateOrder.as_view(), name="order"),
]

templates/public_market.html
{%load static%}
<!DOCTYPE html>

<html lang="en">

<head>
	<title>Coffee - Free Bootstrap 4 Template by Colorlib</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet" />
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet" />
	<link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet" />

	<link rel="stylesheet" href="{% static 'homepage/css/open-iconic-bootstrap.min.css' %}" />
	<link rel="stylesheet" href="{% static 'homepage/css/animate.css' %}" />
	<link rel="stylesheet" href="{% static 'assets/vendor/linearicons/style.css' %}" />
	<link rel="stylesheet" href="{% static 'homepage/css/owl.carousel.min.css' %}" />
	<link rel="stylesheet" href="{% static 'homepage/css/owl.theme.default.min.css' %}" />
	<link rel="stylesheet" href="{% static 'homepage/css/magnific-popup.css' %}" />

	<link rel="stylesheet" href="{% static 'homepage/css/aos.css' %}" />

	<link rel="stylesheet" href="{% static 'homepage/css/ionicons.min.css' %}" />

	<link rel="stylesheet" href="{% static 'homepage/css/bootstrap-datepicker.css' %}" />
	<link rel="stylesheet" href="{% static 'homepage/css/jquery.timepicker.css' %}" />

	<link rel="stylesheet" href="{% static 'homepage/css/flaticon.css' %}" />
	<link rel="stylesheet" href="{% static 'homepage/css/icomoon.css' %}" />
	<link rel="stylesheet" href="{% static 'homepage/css/style.css' %}" />
	<link rel="stylesheet" href="{% static 'assets/css/mine.css'%}" />
</head>

<body>
	<nav class="navbar navbar-expand-sm ftco_navbar  ftco-navbar-light" id="ftco-navbar">
		<div class="container">
			<a class=" navbar-brand title" href="/" style="margin-left: 0;">
				<img src="{%static 'custom_images/LOGO.png'%}" alt="" style="height: 4.5em;" /></a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
				aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="oi oi-menu"></span> Menu
			</button>
			<div class="collapse navbar-collapse" id="ftco-nav">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item active" style="color: white;">
						<a href="/" class="nav-link slide-left-sm" style="font-size: 130%;">Home</a>
					</li>
					<!-- <li class="nav-item"><a href="menu.html" class="nav-link">Menu</a></li> -->

					<li class="nav-item" style="color: white;">
						<a href="{%url 'accounts:about'%}" class="nav-link slide-left-sm"
							style="font-size: 130%;">About</a>
					</li>
					<li class="nav-item" style="color: white;">
						<a href="{% url 'accounts:services' %}" class="nav-link slide-left-sm"
							style="font-size: 130%;">Services</a>
					</li>
					<li class="nav-item" style="color: white;">
						<a href="{% url 'accounts:market' %}" class="nav-link slide-left-sm"
							style="font-size: 130%;">Market</a>
					</li>
					<!-- <li class=" nav-item"><a href="blog.html" class="nav-link">Blog</a></li> -->
					<li class=" nav-item" style="color: white;">
						<a href="{% url 'accounts:contact' %}" class="nav-link slide-left-sm"
							style="font-size: 130%;">Contact</a>
					</li>

				</ul>
			</div>
		</div>
	</nav>
	<!-- END nav -->

	<section class="home-slider owl-carousel">

		<div class="slider-item" style="background-image: url({%static 'homepage/images/bg_1.jpg'%});"
			data-stellar-background-ratio="0.5">
			<div class="overlay"></div>
			<div class="container">
				<div class="row slider-text justify-content-center align-items-center">

					<div class="col-md-7 col-sm-12 text-center ftco-animate">
						<h1 class="mb-3 mt-5 bread">Coffee Market</h1>
						<p>Explore our Market of fresh coffee. We Bring together hundreds of diffrent companies from
							Africa with ready-to-ship coffee</p>
						<p>Be a Member today and get access to our services now.</p>
						<a href="/GetSarted/" class="btn btn-outline-warning py-2 py-3 title">Get started Now</a> <br>
						<br>
						<p class="breadcrumbs"><span class="mr-2"><a href="/">Home</a></span> <span>market</span>
						</p>
					</div>

				</div>
			</div>
		</div>
	</section>

	<section class="ftco-section">
		<div class="container">
			<div class="row d-flex">
				{%for auction in auctions%}
				<div class="col-md-4 d-flex ftco-animate">
					<div class="blog-entry align-self-stretch">
						<a href="{{auction.factory.factory_logo.url}}" class="block-20"
							style="background-image: url({{auction.factory.factory_logo.url}});">
						</a>
						<div class="text py-4 d-block">
							<div class="meta">
								<div><a href="#">{{auction.date}}</a></div>
								<div><a href="#">{{auction.factory}}</a></div>
								<br>
								<div><span>
										{%if auction.factory.rating == 0%}
										<i class="lnr lnr-star-half" style="color: orange;"></i>
										{%elif auction.factory.rating == 1%}
										<i class="lnr lnr-star-half" style="color: orange;"></i>
										<i class="lnr lnr-star-half" style="color: orange;"></i>
										{%elif auction.factory.rating == 2%}
										<i class="lnr lnr-star-half" style="color: orange;"></i>
										<i class="lnr lnr-star-half" style="color: orange;"></i>
										<i class="lnr lnr-star-half" style="color: orange;"></i>
										{%else%}
										rating: <i class="lnr lnr-star" style="color: orange;"></i><i
											class="lnr lnr-star" style="color: orange;"></i><i class="lnr lnr-star"
											style="color: orange;"></i><i class="lnr lnr-star"
											style="color: orange;"></i><i class="lnr lnr-star"
											style="color: orange;"></i>
										{%endif%}
									</span></div>
							</div>
							<h3 class="heading mt-2"><a href="#">{{auction.coffee_type}} Coffee</a></h3>
							<p>${{auction.price_per_tonne}} per tonne</p>
							<span>{{auction.tonnes}} Tonne{{auction.tonnes | pluralize}} | {{auction.tonnes_left}}
								Tonne{{auction.tonnes | pluralize}} left</span>
							<p>{{auction.description}}</p>
							<a href="{%url 'accounts:start'%}" class="btn btn-outline-success" style="width: 100%;">Buy
								Now</a>
						</div>
					</div>
				</div>

				{%endfor%}
			</div>
	</section>

	<footer class="ftco-footer ftco-section img">
		<div class="overlay"></div>
		<div class="container">
			<div class="row mb-5">
				<div class="col-lg-3 col-md-6 mb-5 mb-md-5">
					<div class="ftco-footer-widget mb-4">
						<h2 class="ftco-heading-2">About Us</h2>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia,
							there live the blind texts.</p>
						<ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
							<li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
							<li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
							<li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 mb-5 mb-md-5">
					<div class="ftco-footer-widget mb-4">
						<h2 class="ftco-heading-2">Recent Blog</h2>
						<div class="block-21 mb-4 d-flex">
							<a class="blog-img mr-4" style="background-image: url(images/image_1.jpg);"></a>
							<div class="text">
								<h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a>
								</h3>
								<div class="meta">
									<div><a href="#"><span class="icon-calendar"></span> Sept 15, 2018</a></div>
									<div><a href="#"><span class="icon-person"></span> Admin</a></div>
									<div><a href="#"><span class="icon-chat"></span> 19</a></div>
								</div>
							</div>
						</div>
						<div class="block-21 mb-4 d-flex">
							<a class="blog-img mr-4" style="background-image: url(images/image_2.jpg);"></a>
							<div class="text">
								<h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a>
								</h3>
								<div class="meta">
									<div><a href="#"><span class="icon-calendar"></span> Sept 15, 2018</a></div>
									<div><a href="#"><span class="icon-person"></span> Admin</a></div>
									<div><a href="#"><span class="icon-chat"></span> 19</a></div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-2 col-md-6 mb-5 mb-md-5">
					<div class="ftco-footer-widget mb-4 ml-md-4">
						<h2 class="ftco-heading-2">Services</h2>
						<ul class="list-unstyled">
							<li><a href="#" class="py-2 d-block">Cooked</a></li>
							<li><a href="#" class="py-2 d-block">Deliver</a></li>
							<li><a href="#" class="py-2 d-block">Quality Foods</a></li>
							<li><a href="#" class="py-2 d-block">Mixed</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 mb-5 mb-md-5">
					<div class="ftco-footer-widget mb-4">
						<h2 class="ftco-heading-2">Have a Questions?</h2>
						<div class="block-23 mb-3">
							<ul>
								<li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain
										View, San Francisco, California, USA</span></li>
								<li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929
											210</span></a></li>
								<li><a href="#"><span class="icon icon-envelope"></span><span
											class="text">info@yourdomain.com</span></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 text-center">

					<p>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						Copyright &copy;
						<script>document.write(new Date().getFullYear());</script> All rights reserved | This template
						is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com"
							target="_blank">Colorlib</a>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					</p>
				</div>
			</div>
		</div>
	</footer>



	<!-- loader -->
	<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
			<circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
			<circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
				stroke="#F96D00" /></svg></div>


	<script src="{% static 'homepage/js/jquery.min.js' %}"></script>
	<script src="{% static 'homepage/js/jquery-migrate-3.0.1.min.js' %}"></script>
	<script src="{% static 'homepage/js/popper.min.js' %}"></script>
	<script src="{% static 'homepage/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.easing.1.3.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.stellar.min.js' %}"></script>
	<script src="{% static 'homepage/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'homepage/js/aos.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.animateNumber.min.js' %}"></script>
	<script src="{% static 'homepage/js/bootstrap-datepicker.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.timepicker.min.js' %}"></script>
	<script src="{% static 'homepage/js/scrollax.min.js' %}"></script>
	<script
		src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
	<script src="{% static 'homepage/js/google-map.js' %}"></script>
	<script src="{% static 'homepage/js/main.js' %}"></script>
</body>

</html>

templates/sidebar.html
{% load static %}
<link rel="stylesheet" href="{%static 'assets/css/mine.css'%}">
<!-- LEFT SIDEBAR -->

{%if user.sellerfactoryemployee and user.sellerfactoryemployee.factory.active%}
<div id="sidebar-nav" class="sidebar"
  style="padding-left: 2px; padding-right: 2px; background-color: rgba(0, 0, 0, 0); overflow: scroll; scroll-behavior: smooth; z-index: 0; height: 100%; overflow-x: hidden;">
  <div class="sidebar-scroll">
    <nav>
      <ul class="nav">
        <li style="margin-top: 20px; width: 100%;">
          <a href="/dashboard/" id="home" style="font-size: 120%; ">
            <i class=" lnr lnr-home"></i>
            <span>Dashbord</span>
          </a>
        </li>
        <li style="margin-top: 0px; width: 100%;">
          {%if not user.sellerfactoryemployee.factory.factory_name%}
          <a href="{% url 'transactions:view_market' %}" id="market" style="font-size: 120%; " class="">
            <i class=" lnr lnr-store"></i>
            <span>Market</span></a>
          {%else%}
        <li style="margin-top: 0px; width: 100%;">
          <a href="#subPages" data-toggle="collapse" class="collapsed" style="font-size: 120%; "><i
              class="lnr lnr-plus-circle"></i>
            <span>Auction</span>
            <i class="dropdown-menu"></i></a>
          <div id="subPages" class="collapse">
            <ul class="nav" style="background-color: rgba(0, 0, 0, 0);">
              <li style="border-bottom: 1px rgba(255, 166, 0, 0.514) solid;">
                <a href="{% url 'transactions:add_auction' user.sellerfactoryemployee.factory.factory_name %}"
                  class="ftco-animate" style="font-size: 110%;  color: orange;">Create a new Auction
                </a>
              </li>
              <li style="border-bottom: 1px rgba(255, 166, 0, 0.514) solid; width: 100%;"><a
                  href="{% url 'transactions:auction_history' user.sellerfactoryemployee.factory.factory_name%}"
                  class="ftco-animate" style="font-size: 110%;  color: orange;">View Auction
                  History</a></li>
              <li style="border-bottom: 1px rgba(255, 166, 0, 0.514) solid; width: 100%;"><a
                  href="{% url 'transactions:view_auction'%}" class="ftco-animate livetext-mega"
                  style="font-size: 110%;  color: orange;">Manage Auction</a></li>
            </ul>
          </div>
        </li>
        {% endif %}
        </li>
        <li style="margin-top: 0px; width: 100%;">
          {%if user.sellerfactoryemployee%}
          <a href="{%url 'transactions:charts' user.sellerfactoryemployee.factory.factory_name%}" id="charts" class=""
            style="font-size: 120%; "><i class="lnr lnr-chart-bars"></i> <span>Charts</span></a>
          {%else%}
          <a href="{% url 'transactions:bcharts' user %}" id="charts"><i class="lnr lnr-chart-bars"></i>
            <span style="font-size: 120%; ">Charts</span></a>
          {% endif %}
        </li>

        {%if user.sellerfactoryemployee.factory.factory_name%}
        <li style="margin-top: 0px; width: 100%;">
          <a href="{%url 'transactions:showtransactions' user.sellerfactoryemployee.factory.factory_name%}" class=""
            id="transactions" style="font-size: 120%; "><i class="lnr lnr-cog"></i>
            <span>Transactions</span></a>
        </li>
        {%else%}
        <li style="margin-top: 0px; width: 100%;">
          <a href="{%url 'transactions:showtransactions' user%}" class="" id="transactions"><i
              class="lnr lnr-history"></i>
            <span style="font-size: 120%; ">Transactions</span></a>
        </li>
        {% endif %}
        <li style="margin-top: 0px; width: 100%;">
          <a href="{%url 'transactions:shownotifications' user.username%}" class="" id="noti"><i
              class="lnr lnr-alarm"></i>
            <span style="font-size: 120%; "> Notifications</span></a>
        </li>
        <li style="margin-top: 0px; width: 100%;">
          <a href="/blog" class=""><i class="lnr lnr-dice" id="blog"></i> <span
              style="font-size: 120%; ">Blog</span></a>
        </li>
        <li style="margin-top: 0px; width: 100%;">
          <a href="{%url 'feedback:showfeedback'%}" class="" id="feedback"><i class="lnr lnr-question-circle"></i>
            <span style="font-size: 120%; ">Feedback</span></a>
        </li>
        <li style="margin-top: 0px; width: 100%;">
          <a href="/" class=""><i class="lnr lnr-earth"></i> <span style="font-size: 120%; ">Home</span></a>
        </li>
      </ul>
    </nav>
  </div>
</div>
{%endif%}
{%if user.buyer%}
<div id="sidebar-nav" class="sidebar"
  style="padding-left: 2px; padding-right: 2px; background-color: rgba(0, 0, 0, 0); overflow: scroll; scroll-behavior: smooth; z-index: 0; height: 100%; overflow-x: hidden;">
  <div class="sidebar-scroll">
    <nav>
      <ul class="nav">
        <li style="margin-top: 20px; width: 100%;">
          <a href="/dashboard/" id="home" style="font-size: 120%; ">
            <i class=" lnr lnr-home"></i>
            <span>Dashbord</span>
          </a>
        </li>
        <li style="margin-top: 0px; width: 100%;">
          {%if not user.sellerfactoryemployee.factory.factory_name%}
          <a href="{% url 'transactions:view_market' %}" id="market" style="font-size: 120%; " class="">
            <i class=" lnr lnr-store"></i>
            <span>Market</span></a>
          {%else%}
        <li style="margin-top: 0px; width: 100%;">
          <a href="#subPages" data-toggle="collapse" class="collapsed" style="font-size: 120%; "><i
              class="lnr lnr-plus-circle"></i>
            <span>Auction</span>
            <i class="dropdown-menu"></i></a>
          <div id="subPages" class="collapse">
            <ul class="nav" style="background-color: rgba(0, 0, 0, 0);">
              <li style="border-bottom: 1px rgba(255, 166, 0, 0.514) solid;">
                <a href="{% url 'transactions:add_auction' %}" class="ftco-animate"
                  style="font-size: 110%;  color: orange;">Create a new Auction
                </a>
              </li>
              <li style="border-bottom: 1px rgba(255, 166, 0, 0.514) solid; width: 100%;"><a
                  href="{% url 'transactions:auction_history' user.sellerfactoryemployee.factory.factory_name%}"
                  class="ftco-animate" style="font-size: 110%;  color: orange;">View Auction
                  History</a></li>
              <li style="border-bottom: 1px rgba(255, 166, 0, 0.514) solid; width: 100%;"><a
                  href="{% url 'transactions:view_auction'%}" class="ftco-animate livetext-mega"
                  style="font-size: 110%;  color: orange;">Manage Auction</a></li>
            </ul>
          </div>
        </li>
        {% endif %}
        </li>
        <li style="margin-top: 0px; width: 100%;">
          {%if user.sellerfactoryemployee%}
          <a href="{%url 'transactions:charts' user.sellerfactoryemployee.factory.factory_name%}" id="charts" class=""
            style="font-size: 120%; "><i class="lnr lnr-chart-bars"></i> <span>Charts</span></a>
          {%else%}
          <a href="{% url 'transactions:bcharts' user %}" id="charts"><i class="lnr lnr-chart-bars"></i>
            <span style="font-size: 120%; ">Charts</span></a>
          {% endif %}
        </li>

        {%if user.sellerfactoryemployee.factory.factory_name%}
        <li style="margin-top: 0px; width: 100%;">
          <a href="{%url 'transactions:showtransactions' user.sellerfactoryemployee.factory.factory_name%}" class=""
            id="transactions" style="font-size: 120%; "><i class="lnr lnr-cog"></i>
            <span>Transactions</span></a>
        </li>
        {%else%}
        <li style="margin-top: 0px; width: 100%;">
          <a href="{%url 'transactions:showtransactions' user%}" class="" id="transactions"><i
              class="lnr lnr-history"></i>
            <span style="font-size: 120%; ">Transactions</span></a>
        </li>
        {% endif %}
        <li style="margin-top: 0px; width: 100%;">
          <a href="{%url 'transactions:shownotifications' user.username%}" class="" id="noti"><i
              class="lnr lnr-alarm"></i>
            <span style="font-size: 120%; "> Notifications</span></a>
        </li>
        <li style="margin-top: 0px; width: 100%;">
          <a href="/blog" class=""><i class="lnr lnr-dice" id="blog"></i> <span
              style="font-size: 120%; ">Blog</span></a>
        </li>
        <li style="margin-top: 0px; width: 100%;">
          <a href="{%url 'feedback:showfeedback'%}" class="" id="feedback"><i class="lnr lnr-question-circle"></i>
            <span style="font-size: 120%; ">Feedback</span></a>
        </li>
        <li style="margin-top: 0px; width: 100%;">
          <a href="/" class=""><i class="lnr lnr-earth"></i> <span style="font-size: 120%; ">Home</span></a>
        </li>
      </ul>
    </nav>
  </div>
</div>
{%endif%}
<div class="modal-transparent" id="loadingDiv" style="top: 10%;">
  <div class="modal-content2" style="background-color: rgb(255, 255, 255); border-radius: 15px;">
    <span class="title" style="color: black;"> <i class="lnr lnr-hourglass fade-loop" style="font-size: 170%;"></i>
      Processing please
      wait...</span>
    <img src="{%static 'assets/img/loading.gif'%}" alt="loading" height="100px">
  </div>
</div>

<div id="myModal" class="modal dark" style="top: 10%;">
  <div class="modal-content" style="background-color: rgba(17, 15, 15, 0.904);">
    <span class="close">&times;</span>
    <h3 class="orange">Warning!</h3>
    <h4 style="color: rgb(82, 78, 78);">Are you sure you want to delete this Auction</h4>
    <span>please note, if you do so, all orders and associated transactions will be discarded.Proceed
      with
      caution!</span>
    <hr>
    <div style="text-align: center;">
      <button class="btn btn-primary" id="yes">Yes, am sure!</button>
      <button class="btn btn-danger" id="exit">No, Cancel!</button>
    </div>
  </div>
</div>
<script>
  if (document.URL.includes('dash'))
  {
    home = document.getElementById('home')
    home.classList.add('active')
    home.style.color = 'orange'
    console.log('home')
  } else if (document.URL.includes('charts'))
  {
    charts = document.getElementById('charts')
    charts.style.color = 'orange'
    charts.classList.add('active')
  } else if (document.URL.includes('auction'))
  {
    auction = document.getElementById('auction')
    auction.style.color = 'orange'
    auction.classList.add('active')
  } else if (document.URL.includes('market'))
  {
    auction = document.getElementById('market')
    auction.style.color = 'orange'
    auction.classList.add('active')
  } else if (document.URL.includes('transactions/{{user.username}}'))
  {
    auction = document.getElementById('transactions')
    auction.style.color = 'orange'
    auction.classList.add('active')
  } else if (document.URL.includes('feedback'))
  {
    auction = document.getElementById('feedback')
    auction.style.color = 'orange'
    auction.classList.add('active')
  } else if (document.URL.includes('notification'))
  {
    auctiond = document.getElementById('noti')
    auctiond.style.color = 'orange'
    auctiond.classList.add('active')
  }
  loadingModal = document.getElementById('loadingDiv')
  function showLoading()
  {
    loadingModal.style.display = "block";
  }
  function hideLoading()
  {
    loadingModal.style.display = "none";
  }
  document.getElementById('home').onclick = function ()
  {
    showLoading()
  }
  document.getElementById('charts').onclick = function ()
  {
    showLoading()
  }
  document.getElementById('market').onclick = function ()
  {
    showLoading()
  }
  document.getElementById('auction').onclick = function ()
  {
    showLoading()
  }
  document.getElementById('notifications').onclick = function ()
  {
    showLoading()
  }
</script>
<!-- END LEFT SIDEBAR -->